# Generated by Django 4.2.16 on 2024-11-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details_image',
            field=models.ImageField(default='default.jpg', upload_to='project/images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='project/images'),
        ),
    ]
